stages:
  - name: select
    dependencies: [init]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        inputfile: {stages: 'init', output: inputfile, unwrap: true }
        outputfile: '{workdir}/select_signal.root'
        region: signal
        variations: {stages: init, output: shapevar, unwrap: true}
      step: {$ref: steps.yml#/select_mc}
      scatter:
        method: zip
        parameters: [inputfile]

  - name: merge
    dependencies: [select]
    scheduler:
      scheduler_type: multistep-stage
      batchsize: 2
      parameters:
        inputs: {stages: 'select', output: outputfile}
        mergedfile: '{workdir}/merged.root'
      step: {$ref: steps.yml#/merge_root}
      scatter:
        method: zip
        parameters: [inputs]

  - name: hist
    dependencies: [merge]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        inputfile: {stages: 'merge', output: mergedfile}
        outputfile: '{workdir}/hist.root'
        name: {stages: init, output: mcname, unwrap: true}
        weight: {stages: init, output: mcweight, unwrap: true}
        variations: [nominal]
      step: {$ref: steps.yml#/histogram}
      scatter:
        method: zip
        parameters: [inputfile]
